### ISSUE TITLE
Don't put So-Nav-Menu on the top

### ISSUE THREAD

**Issue by leolorenzoluis** [jbonfardeci/ShockoutForms#10]
Hi,

Is there a way to control where so-nav-menu is generated. I don't want it always on the top. I want it inside the form.

**Comment by leolorenzoluis** [comment]
Nevermind, including includeNavigationMenu: false in constructor does it.

**Comment by jbonfardeci** [comment]
I plan to make this an option where you can manually place the <so-nav-menu
/> anywhere in your HTML.
