### ISSUE TITLE
PostRender function 

### ISSUE THREAD

**Issue by leolorenzoluis** [jbonfardeci/ShockoutForms#11]
PostRender function fires too early. I was expecting PostRender to fire after KnockOut template is done?

**Comment by jbonfardeci** [comment]
Hi there. It sounds like you may have an issue with an asynchronous method.
Postrender is called after all elements are added to the DOM but you may
have another async method where the data hasn't loaded when expected. In
every case where I'm loading async data, say from another list, I store the
results in a Knockout observable array on the callback. This guarantees the
data will be available on the Knockout view model when it does load.

**Comment by leolorenzoluis** [comment]
Does this mean that the check box multi group needs its own ko.observableArray so that I can do stuff after shockout template is applied?

**Comment by leolorenzoluis** [comment]
As far as I know I am not calling any asynchronous calls right now to load the data. I get the observable part to listen for changes. My scenario is like this:

I am using check box multi group that requires multiple selection, and I need to apply some changes to the rendered template. I tried subscribing to the FieldName. However, it doesn't fire since there are no changes to it. Could you show me how to handle when the check boxes are rendered?

**Comment by leolorenzoluis** [comment]
I'm using Material Design for Bootstrap, and I have to call $.material.init() after the check boxes has rendered the template with the model. Do you know if it's possible or do I have to tweak SO?
