### ISSUE TITLE
Managed metadata column as input

### ISSUE THREAD

**Issue by leolorenzoluis** [jbonfardeci/ShockoutForms#13]
Is there a way to pull in managed metadata term as input or term sets?

**Comment by jbonfardeci** [comment]
Not with REST in 2010. It may be possible in 2013 with the new API.

**Comment by leolorenzoluis** [comment]
Okay good to know. Is there a way to reach you out if I bave questions? I am really considering this as the framework to use rather than built in list forms and infopath. I may branch this one and remove the bootstrap dependencies.

**Comment by leolorenzoluis** [comment]
What about using the TaxonomyClientService ?

https://social.technet.microsoft.com/Forums/office/en-US/632190d9-663b-4ea6-82e8-5c1e7f2f57c5/managed-metadata-columns-infopath?forum=sharepointadminprevious

**Comment by jbonfardeci** [comment]
My email is john.bonfardeci@gmail.com mailto:john.bonfardeci@gmail.com. I’ll answer what I can about existing features. I have a heavy workload myself.

**Comment by jbonfardeci** [comment]
Sounds like something you could implement yourself in the postRender callback. I have no plans to add such a component nor the time.
