### ISSUE TITLE
IE 10/11 is not supported

### ISSUE THREAD

**Issue by leolorenzoluis** [jbonfardeci/ShockoutForms#15]
Rendering in IE with the given example does not look right like the screenshot.

![beh](https://cloud.githubusercontent.com/assets/15150044/15229256/382c6f28-185e-11e6-8e85-2383a2bc20ec.png)

**Comment by jbonfardeci** [comment]
IE 10 and up are supported. Are you using the provided Shockout master page? The screenshot on the homepage was taken in SP 2013 but it looks the same in another SP 2010 farm. The recommended set up is to have all of your forms in a document library using the Shockout master page. This master page is minimal and uses non of the SP CSS or JS. If you need to create a form using one of the SP master pages, you may have to add your own CSS.

**Comment by leolorenzoluis** [comment]
Yes, I am using the Shockout master page.
