### ISSUE TITLE
Supervisor input doesn't display correctly

### ISSUE THREAD

**Issue by leolorenzoluis** [jbonfardeci/ShockoutForms#16]
I am using claims based authentication. I can get the supervisors without a problem. However, once I focus out of the textbox, the displayed text is just 'i:0'

**Comment by jbonfardeci** [comment]
It’s likely the formatting of the default account name in your dev environment. VM? When account names are sent over from REST, they look like `1;#DOMAIN\username` where ‘1’ could be any user ID number. This of course can change based on the format you have selected for the person field in the SP list. The knockout component tries to render the display name for regular users.

**Comment by leolorenzoluis** [comment]
Well it looks like it is pulling accounts from the active directory and the claims based authentication users. The claims based users are what I am interested in. However, like I said it just displays i:0 though it is valid. It also displays properly on edit. 

This only happens when you create a new item.

**Comment by bnsc** [comment]
You are talking about a so-person-field, right?

If so, do you see a list of users once you type at least three characters?

On Mon, May 16, 2016 at 4:36 PM, leolorenzoluis notifications@github.com
wrote:

> Well it looks like it is pulling accounts from the active directory and
> the claims based authentication users. The claims based users are what I am
> interested in. However, like I said it just displays i:0 though it is
> valid. It also displays properly on edit.
> 
> This only happens when you create a new item.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jbonfardeci/ShockoutForms/issues/16#issuecomment-219555829

## 

+Bill

https://plus.google.com/u/0/+BillCochranRocks/posts
https://www.linkedin.com/in/bnscbill
http://stackoverflow.com/users/4347437/bill

**Comment by leolorenzoluis** [comment]
Yes, I do see it. I am able to pick and choose. However, once I pick something the way it splits in onChangeSpPersonEvent, it just displays 'i:0'
