### ISSUE TITLE
Validation doesn't work on Submit

### ISSUE THREAD

**Issue by leolorenzoluis** [jbonfardeci/ShockoutForms#17]
Using 

`<so-checkbox-group params="val: Changes"></so-checkbox-group>`

It doesn't validate the check boxes.

**Comment by jbonfardeci** [comment]
Why do you think that is? It's explained in the doc and is intentional.

**Comment by leolorenzoluis** [comment]
The documentation says on save. I understand Save won't balidate but Submit should?

**Comment by leolorenzoluis** [comment]
'if (isSubmit && !self.formIsValid(vm)) {
                    return;
                }'

It does validate on other fields but not this so template? Could you show me which documentation you're referring to?

**Comment by jbonfardeci** [comment]
Validation occurs on Submit but not Save. This allows users to fill out long forms and save their work in progress. In our organization, sometimes an exec will have a form open the whole day as they deal with interruptions constantly. 

If using this workflow, you must add a step in your SharePoint workflow that waits until IsSubmitted (boolean Yes/No) is equal to true; then the remaining workflow steps occur.

For Knockout components, you must set the option `required: true`. For other non-knockout components, add there required attribute to the element.

**Comment by leolorenzoluis** [comment]
Right, I guess GitHub didn't update my Title. I originally had it as **Validation not occuring on Save**, but I changed it to **Validation not occuring on Submit**. When I click submit, it validates on other fields like so-text-field but not so-checkbox-group even adding required attribute.
