### ISSUE TITLE
Can't activate template with example

### ISSUE THREAD

**Issue by leolorenzoluis** [jbonfardeci/ShockoutForms#5]
Trying to run it against SP 2010 Service Pack 2 with latest cumulative updates. I assume I have the wrong template to begin with? I tried blank and team site.

**Comment by bnsc** [comment]
I may need to get more information from you to be able to help you.

Can you send a screenshot of the list settings and post the source of your page?  Also, if this is a publicly accessible site, let me know the URL.  

Give me as much info as you can so I can lend a hand.  
Thank you,
Bill

**Comment by leolorenzoluis** [comment]
Hmm, sorry this is just in a dev machine. I wanted to try out the framework. 

My repro steps:
1. Created a web application
2. Created a blank site
3. Site settings -> Solutions -> Upload solution
4. Activate button is disabled

I turned on Sandboxed Code Services.

**Comment by leolorenzoluis** [comment]
Silly me. It has to be on list template. Sorry. Closing this issue.

Quick question, formId 'ShockoutSpForm; Where is this stored/set?

And the example doesn't work with the given master page. Is there a step by step to get the example working?
