### ISSUE TITLE
Nav menu

### ISSUE THREAD

**Issue by leolorenzoluis** [jbonfardeci/ShockoutForms#7]
On the given example, is there a way to customize the navbar header? Instead of a list of URL, it will be an accordion?

**Comment by bnsc** [comment]
This is possible.  

Search the .js for 'Templates.soNavMenuControl' and 'Templates.soNavMenu'.  These are the templates for the menu (about line 3292).  If you modify the template, you can get the desired accordion layout.

I hope this helps you.
Thank you,
Bill

**Comment by lllpsi** [comment]
Does modifying the templates to not use bootstrap removes all bootstrap dependencies?
